/**
 * Emit `src/data/tenant-data.ts` in the tenant fork.
 */

import type { PageDef, BlogPost, Testimonial, TeamMember, Service, Product } from "./types.js";

export interface EmitDataInput {
  pages: PageDef[];
  blog: BlogPost[];
  testimonial: Testimonial[];
  team: TeamMember[];
  service: Service[];
  product: Product[];
  siteName: string;
  lang: string;
  dir: "ltr" | "rtl";
  navigation: Array<{ label: string; href: string }>;
}

export function emitTenantData(input: EmitDataInput): string {
  const header = `/**
 * tenant-data.ts — GENERATED by @hostaposta/generate.
 * Overwriting this file is idempotent; do not hand-edit — changes will be
 * clobbered on next generation.
 */
import type { TenantData } from './types.js';

export const TENANT_DATA: TenantData = `;

  const body = JSON.stringify(
    {
      lang: input.lang,
      dir: input.dir,
      settings: {
        siteName: input.siteName,
        navigation: input.navigation,
      },
      pages: input.pages,
      collections: {
        blog: input.blog,
        testimonial: input.testimonial,
        team: input.team,
        service: input.service,
        product: input.product,
      },
    },
    null,
    2,
  );

  return `${header}${body};\n`;
}
