/**
 * Tenant data shapes.
 *
 * Every block instance points at a file under `src/components/blocks/tenant/`
 * by name. Block components are per-tenant — generated by HostaPosta's
 * Block Generator from the source site. The template's pristine ships with
 * a handful of example blocks so the demo renders without regeneration.
 */

export interface GeneratedBlockInstance {
  /** Filename (without extension) under `src/components/blocks/tenant/`. */
  componentName: string;
  /** Props passed to the component at render time. Shape matches whatever
   *  the component declares in its Astro `interface Props`. */
  props: Record<string, unknown>;
}

// ── Collections ─────────────────────────────────────────────────

export interface BlogPost {
  title: string;
  slug: string;
  excerpt?: string;
  body?: string;
  author?: string;
  publishDate?: string;
  featuredImage?: string;
  tags?: string[];
}

export interface Testimonial {
  quote: string;
  author: string;
  role?: string;
  company?: string;
  avatar?: string;
  featured?: boolean;
}

export interface TeamMember {
  name: string;
  role?: string;
  category?: "team" | "leadership" | "advisor" | "partner";
  bio?: string;
  photo?: string;
  social?: Array<{ platform: string; url: string }>;
}

export interface Service {
  name: string;
  slug: string;
  description: string;
  icon?: string;
  features?: string[];
}

export interface Product {
  name: string;
  slug: string;
  price?: string | number;
  currency?: string;
  image?: string;
  description?: string;
  category?: string;
  inStock?: boolean;
  features?: string[];
}

// ── Site settings ───────────────────────────────────────────────

export interface SiteSettings {
  siteName: string;
  tagline?: string;
  navigation: Array<{ label: string; href: string }>;
  footerText?: string;
}

export interface PageDef {
  slug: string;
  title: string;
  description?: string;
  dataPage?: string;
  blocks: GeneratedBlockInstance[];
}

export interface TenantData {
  settings: SiteSettings;
  pages: PageDef[];
  collections: {
    blog?: BlogPost[];
    testimonial?: Testimonial[];
    team?: TeamMember[];
    service?: Service[];
    product?: Product[];
  };
  lang: string;
  dir: "ltr" | "rtl";
}
